## Script to Create a XYZ Box and Target coordinates for export to Simulator

### Import High Reward List

In [1]:
import numpy as np
import csv
import glob

In [2]:
highRewardList = np.load('../outputs/highRewardList.npy')
print(highRewardList)

[    0     3     5 ... 28226 28229 28246]


In [3]:
#Create a list of all file names
filenames_list = sorted(glob.glob('../her_throw1_playback/steps/*monitor.csv'))
print('Length of file: ',len(filenames_list)) 
print(filenames_list[500])

Length of file:  28256
../her_throw1_playback/steps/000000000500.monitor.csv


In [10]:
#Create a list of Goal XYZ coordinates and Box XYZ Coordinates from HighRewardList

goalXYZ=[]
boxXYZ=[]

highRewardList = np.array(highRewardList)
print(type(highRewardList))

for file in highRewardList:

    with open(filenames_list[file]) as csv_file:
        episodeMTX = list(csv.reader(csv_file, delimiter=','))
    del episodeMTX[:2]
    
    step = episodeMTX[0]
    goalXYZ.append((np.double(step[11]),np.double(step[12]),np.double(step[13])))
    boxXYZ.append((np.double(step[8]),np.double(step[9]),np.double(step[10])))

goalXYZ=np.array(goalXYZ)
boxXYZ=np.array(boxXYZ)
highRewCoords = np.column_stack((boxXYZ,goalXYZ))

<class 'numpy.ndarray'>


In [11]:
print(highRewCoords)
#np.save('boxXYZgoalXYZ.npy', highRewCoords)

[[1.06580355 0.84566025 0.36473541 1.31892696 0.79792148 0.36469864]
 [1.08352581 0.77862728 0.36473541 1.39297097 0.71238377 0.36469864]
 [1.07729884 0.80242089 0.36473541 1.48101534 0.81746987 0.36469864]
 ...
 [1.04194328 0.66513661 0.36473541 1.26627969 0.6107252  0.36469864]
 [1.02773669 0.84901049 0.36473541 1.27746939 0.65663477 0.36469864]
 [0.96005696 0.84771458 0.36473541 1.43546153 0.81027629 0.36469864]]


## Script to Obtain xyz-coordinates of Goal and Box for Individual Episodes - from filenames_list

In [12]:
#1 Define Custom Variety List


[270, 7220, 7511, 8348, 8834]


In [13]:
#2 Script to populate boxXYZ list and goal XYZ list, and combine them
boxXYZ=[]
goalXYZ=[]

for file in varietyList:

    with open(filenames_list[file]) as csv_file:
        episodeMTX = list(csv.reader(csv_file, delimiter=','))
    del episodeMTX[:2]
    
    step = episodeMTX[0]
    goalXYZ.append((np.double(step[11]),np.double(step[12]),np.double(step[13])))
    boxXYZ.append((np.double(step[8]),np.double(step[9]),np.double(step[10])))

goalXYZ=np.array(goalXYZ)
boxXYZ=np.array(boxXYZ)
customList = np.column_stack((boxXYZ,goalXYZ))
print(customList)

[[0.90883628 0.84040299 0.36473541 1.36775149 0.70287    0.36469864]
 [1.08354711 0.69325057 0.36473541 1.36070779 0.81162762 0.36469864]
 [1.08251427 0.6991847  0.36473541 1.43596654 0.81338913 0.36469864]
 [1.05654836 0.82640226 0.36473541 1.34551548 0.69243773 0.36469864]
 [0.88773965 0.78044228 0.36473541 1.29340094 0.64843517 0.36469864]]


In [4]:
#3 Save HighRewardList

#np.save('../outputs/boxXYZgoalXYZ_1.npy',highRewCoords)
#np.save('../outputs/boxXYZgoalXYZ_single.npy',highRewCoords)